const API_URL="https://script.google.com/macros/s/AKfycbzY8la37LIrnj4T6Uy4lUL5DY21NzpLnaNfbg3TZST7KpaYTesaQ3qFbCqk8QsQSZT0PA/exec";
let faultRows=[],siteRows=[],technicianRows=[],technicianOptions=[],siteChanges={},technicianChanges={};
function safe(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function msg(text,ok){const b=document.getElementById("message");if(!b)return;b.textContent=text;b.className="message "+(ok?"ok":"err");setTimeout(()=>b.className="message",5000);}
function apiGet(action,params={}){return new Promise((resolve,reject)=>{const cb="cb_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),q=new URLSearchParams({action,callback:cb,...params}),timer=setTimeout(()=>{clean();reject(new Error("API request timed out."));},30000);function clean(){clearTimeout(timer);delete window[cb];s.remove();}window[cb]=r=>{clean();if(!r||r.success===false){reject(new Error(r?.message||"API request failed."));return;}resolve(r.data);};s.onerror=()=>{clean();reject(new Error("Unable to connect to Apps Script API."));};s.src=API_URL+"?"+q.toString();document.body.appendChild(s);});}
function showTab(id,btn){document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(btn)btn.classList.add('active');if(id==='dashboardTab')loadDashboard();if(id==='faultTab'&&!faultRows.length)loadFaults();if(id==='siteTab'&&!siteRows.length)loadSites();if(id==='techTab'&&!technicianRows.length)loadTechnicians();}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v??"";}
async function loadDashboard(){const l=document.getElementById('dashboardLoading'),c=document.getElementById('dashboardContent');l.style.display='block';c.classList.add('hidden');try{const d=await apiGet('dashboard');setText('totalFaults',d.totalFaults||0);setText('openFaults',d.open||0);setText('progressFaults',d.inProgress||0);setText('closedFaults',d.closed||0);setText('materialFaults',d.waitingMaterial||0);setText('vendorFaults',d.waitingVendor||0);setText('totalSites',d.totalSites||0);setText('totalTechnicians',d.totalTechnicians||0);setText('activeFaults',Number(d.open||0)+Number(d.inProgress||0));setText('closureRate',(Number(d.totalFaults)?Math.round(Number(d.closed||0)/Number(d.totalFaults)*100):0)+'%');setText('lastRefresh',new Date().toLocaleString());l.style.display='none';c.classList.remove('hidden');}catch(e){l.innerHTML='❌ Dashboard Error: '+safe(e.message||e);}}
async function loadFaults(){const b=document.getElementById('faultBody');b.innerHTML='<tr><td colspan="10" class="loading">Loading faults...</td></tr>';try{const d=await apiGet('faults');faultRows=Array.isArray(d)?d:(d?.rows||[]);populateFaultTechnicianFilter();renderFaults(faultRows);}catch(e){b.innerHTML='<tr><td colspan="10" class="loading">❌ '+safe(e.message||e)+'</td></tr>';}}
function populateFaultTechnicianFilter(){const s=document.getElementById('faultTechFilter'),old=s.value,n=[...new Set(faultRows.map(r=>String(r.technician||'').trim()).filter(Boolean))].sort();s.innerHTML='<option value="">All Technicians</option>'+n.map(x=>'<option value="'+safe(x)+'">'+safe(x)+'</option>').join('');s.value=old;}
function opt(v,c){return '<option value="'+safe(v)+'" '+(v===c?'selected':'')+'>'+safe(v)+'</option>';}
function renderFaults(rows){setText('faultCount','Showing '+rows.length+' faults');const b=document.getElementById('faultBody');if(!rows.length){b.innerHTML='<tr><td colspan="10" class="loading">No fault records found.</td></tr>';return;}b.innerHTML=rows.map(r=>{const st=String(r.status||'Open');return '<tr><td>'+safe(r.entryDate)+'</td><td>'+safe(r.technician)+'</td><td>'+safe(r.site)+'</td><td>'+safe(r.dgMake)+'</td><td>'+safe(r.dgKva)+'</td><td>'+safe(r.fault)+'</td><td>'+safe(r.remark)+'</td><td>'+safe(r.docket)+'</td><td>'+safe(r.faultDate)+'</td><td><select class="status-select" data-row="'+Number(r.rowNumber||0)+'" onchange="updateFaultStatus(this)">'+opt('Open',st)+opt('In Progress',st)+opt('Closed',st)+opt('Waiting for Material',st)+opt('Waiting for Vendor',st)+'</select></td></tr>';}).join('');}
function filterFaults(){const q=document.getElementById('faultSearch').value.toLowerCase().trim(),t=document.getElementById('faultTechFilter').value.toLowerCase(),s=document.getElementById('faultStatusFilter').value.toLowerCase();renderFaults(faultRows.filter(r=>{const a=[r.entryDate,r.technician,r.site,r.dgMake,r.dgKva,r.fault,r.remark,r.docket,r.faultDate,r.status].join(' ').toLowerCase();return(!q||a.includes(q))&&(!t||String(r.technician||'').toLowerCase()===t)&&(!s||String(r.status||'').toLowerCase()===s);}));}
async function updateFaultStatus(el){const row=Number(el.dataset.row),value=el.value;if(!row){msg('❌ Fault row number missing.',false);return;}el.disabled=true;try{const r=await apiGet('updateFaultStatus',{row,value});if(!r||r.success===false)throw new Error(r?.message||'Status update failed.');msg('✅ Fault status updated.',true);await Promise.all([loadFaults(),loadDashboard()]);}catch(e){msg('❌ '+(e.message||e),false);}finally{el.disabled=false;}}
async function loadSites(){const b=document.getElementById('siteBody');b.innerHTML='<tr><td colspan="3" class="loading">Loading sites...</td></tr>';try{const d=await apiGet('sites');siteRows=Array.isArray(d)?d:(d?.rows||[]);await loadTechnicianNames();renderSites(siteRows);}catch(e){b.innerHTML='<tr><td colspan="3" class="loading">❌ '+safe(e.message||e)+'</td></tr>';}}
async function loadTechnicianNames(){try{const d=await apiGet('technicians'),a=Array.isArray(d)?d:(d?.rows||[]);technicianOptions=[...new Set(a.map(r=>String(r.technician||r.name||r.technicianName||r[0]||'')).filter(Boolean))].sort();}catch(e){technicianOptions=[];}}
function renderSites(rows){setText('siteCount','Showing '+rows.length+' sites');const b=document.getElementById('siteBody');if(!rows.length){b.innerHTML='<tr><td colspan="3" class="loading">No sites found.</td></tr>';return;}b.innerHTML=rows.map(r=>{const site=String(r.sapId||r.site||r.siteId||''),cur=String(r.technician||''),opts='<option value="">-- Unassigned --</option>'+technicianOptions.map(n=>'<option value="'+safe(n)+'" '+(n===cur?'selected':'')+'>'+safe(n)+'</option>').join('');return '<tr><td>'+safe(site)+'</td><td>'+safe(r.siteType)+'</td><td><select class="select editable" data-site="'+safe(site)+'" onchange="markSiteChange(this)">'+opts+'</select></td></tr>';}).join('');}
function markSiteChange(el){siteChanges[el.dataset.site]=el.value;}
function filterSites(){const q=document.getElementById('siteSearch').value.toLowerCase().trim();renderSites(siteRows.filter(r=>[r.sapId,r.site,r.siteId,r.siteType,r.technician].join(' ').toLowerCase().includes(q)));}
async function saveSiteChanges(){const keys=Object.keys(siteChanges);if(!keys.length){msg('No site changes to save.',false);return;}const btn=document.getElementById('saveSitesBtn');btn.disabled=true;let failed=0;try{await Promise.all(keys.map(async site=>{try{const r=await apiGet('updateSiteTechnician',{pin:'',site,technician:siteChanges[site]});if(!r||r.success===false)failed++;}catch(e){failed++;}}));if(failed)msg('⚠ '+failed+' site change(s) failed.',false);else{siteChanges={};msg('✅ All site technician changes saved.',true);await Promise.all([loadSites(),loadDashboard()]);}}finally{btn.disabled=false;}}
async function addTechnician(){const i=document.getElementById('newTechName'),name=String(i.value||'').trim();if(!name){msg('Please enter Technician Name.',false);i.focus();return;}try{const r=await apiGet('addNewTechnician',{name});if(!r||r.success===false)throw new Error(r?.message||'Failed to add technician.');document.getElementById('newTechResult').textContent='✅ '+name+' added successfully. Link: '+(r.link||'');msg('✅ Technician added successfully.',true);i.value='';await Promise.all([loadTechnicians(),loadSites(),loadDashboard()]);}catch(e){msg('❌ '+(e.message||e),false);}}
async function loadTechnicians(){const b=document.getElementById('techBody');b.innerHTML='<tr><td colspan="4" class="loading">Loading technicians...</td></tr>';try{const d=await apiGet('technicians');technicianRows=Array.isArray(d)?d:(d?.rows||[]);technicianChanges={};renderTechnicians(technicianRows);}catch(e){b.innerHTML='<tr><td colspan="4" class="loading">❌ '+safe(e.message||e)+'</td></tr>';}}
function renderTechnicians(rows){setText('techCount','Showing '+rows.length+' technicians');const b=document.getElementById('techBody');if(!rows.length){b.innerHTML='<tr><td colspan="4" class="loading">No technician records found.</td></tr>';return;}b.innerHTML=rows.map((r,i)=>{const n=r.technician||r.name||r.technicianName||r[0]||'',c=r.siteCount!=null?r.siteCount:(r.count!=null?r.count:''),t=r.token||r.Token||r[2]||'',l=r.link||r.technicianLink||r.url||r[3]||'';return '<tr><td><input class="input editable" data-index="'+i+'" value="'+safe(n)+'" onchange="markTechChange(this)"></td><td>'+safe(c)+'</td><td>'+safe(t)+'</td><td class="link">'+(l?'<a href="'+safe(l)+'" target="_blank" rel="noopener">'+safe(l)+'</a>':'')+'</td></tr>';}).join('');}
function markTechChange(el){technicianChanges[Number(el.dataset.index)]=el.value.trim();}
function filterTechnicians(){const q=document.getElementById('techSearch').value.toLowerCase().trim();renderTechnicians(technicianRows.filter(r=>[r.technician,r.name,r.technicianName,r.token,r.Token].join(' ').toLowerCase().includes(q)));}
async function saveTechnicianChanges(){const keys=Object.keys(technicianChanges);if(!keys.length){msg('No technician changes to save.',false);return;}const btn=document.getElementById('saveTechBtn');btn.disabled=true;let failed=0;try{await Promise.all(keys.map(async k=>{const r=technicianRows[Number(k)],token=r.token||r.Token||r[2]||'';try{const x=await apiGet('updateTechnicianName',{token,name:technicianChanges[k]});if(!x||x.success===false)failed++;}catch(e){failed++;}}));if(failed)msg('⚠ Some technician changes failed.',false);else{technicianChanges={};msg('✅ Technician changes saved.',true);await Promise.all([loadTechnicians(),loadSites(),loadDashboard()]);}}finally{btn.disabled=false;}}
function downloadTableExcel(id,name){const table=document.getElementById(id);if(!table){msg('Table not found.',false);return;}const clone=table.cloneNode(true);clone.querySelectorAll('select,input').forEach(e=>{e.parentElement.textContent=e.value;});const html='<!DOCTYPE html><html><head><meta charset="UTF-8"><style>table{border-collapse:collapse}th,td{border:1px solid #999;padding:6px}th{background:#123f7a;color:#fff}</style></head><body>'+clone.outerHTML+'</body></html>',blob=new Blob([html],{type:'application/vnd.ms-excel'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
async function downloadDashboardExcel(){try{const r=await apiGet('dashboardExcel');if(!r||!r.base64)throw new Error('Excel file data not received.');const bin=atob(r.base64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='DG_Fault_Tracker_Admin_'+new Date().toISOString().slice(0,10)+'.xlsx';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){msg('❌ Excel download failed: '+(e.message||e),false);}}
window.addEventListener('load',loadDashboard);
